### ISSUE TITLE
Possible mis-identification of feed type

### ISSUE THREAD

**Issue by toppa** [feedjira/feedjira#176]
I'm not sure if this is an issue with Feedzirra or MediaFed, but Feedzirra is trying to parse these as iTunes feeds, and they are not iTunes feeds:

http://rss.nytimes.com/services/xml/rss/nyt/NYRegion.xml
http://feeds.gothamistllc.com/gothamist05

The problem is the opening rss tag has an itunes podcast DTD in it, so it passes the regex that's checking for itunes feeds. But here's the odd thing: I ran into this problem only after upgrading to 0.2.0.rc2. I got an error trying to use entry_id, which doesn't get defined in the iTunes RSS entry parser:

NoMethodError: undefined method `entry_id' for #Feedzirra::Parser::ITunesRSSItem:0x00000008b60f00

We were previously using version 0.1.2 and did not get this error with those feeds. The regex looks the same in both versions, and both versions don't define entry_id for iTunes, so offhand I'm puzzled why it wasn't a problem with the older version as well...

But the bigger question is whether those feeds are even identifying themselves correctly - feedback appreciated.

**Comment by davemate23** [comment]
I've just started using the gem and this still seems to be occurring for me. I assume this issue was not sorted for version 2.0?

**Comment by davemate23** [comment]
Has there been any updates on this issue? I just built an aggregated new reader app and it seems to have the same issues?

**Comment by mikeastock** [comment]
@davemate23 you can remove the iTunes parser by configuring Feedjira as such:

```ruby
Feedjira.configure do |config|
  config.parsers = [
    Feedjira::Parser::RSSFeedBurner,
    Feedjira::Parser::GoogleDocsAtom,
    Feedjira::Parser::AtomYoutube,
    Feedjira::Parser::AtomFeedBurner,
    Feedjira::Parser::Atom,
    Feedjira::Parser::RSS
  ]
end
```
